### PR TITLE
[WIP] Provide dem as a docker image.

### PR DESCRIPTION
**Pull request by blambeau**
@ygu @llambeau I start a conversation here: I'd like to have an easy way to convert a markdown document (blog post, idea, whatever) to a beautiful styled .pdf or .html document.

So, the branch aims at providing an easy-to-use way of doing that on top of `dem-bs`.

- [ ] @llambeau maybe we should challenge my Dockerfile. I tried starting from alpine, but without success. Maybe a multi-stage build would be great, but then we need to extract both `dem` and `weasyprint` statically and I'm not sure I know how to do that
- [ ] @ygu If you look at the README, you'll see that the `dem print` scenario is unnecessary complex. Any reason why `dem print` does not generate pdf on standard output?

### CODE REVIEW

**Review by llambeau — COMMENTED** [review]
I'd suggest to 

* Use multistage builds to avoid shipping a massive image for a tiny command line tool
* Expose dem as an ENTRYPOINT rather than the CMD, so that we can directly pass the arguments and options to dem

**Comment by blambeau** [comment]
@llambeau see my PR comment above. I might need a little help here.

**Comment by llambeau** [comment]
I'll gladly help today, after I finish my similar challenging refactoring of startback's dockerification ;-)

**Comment by ygu** [comment]
@blambeau I don't get the complexity of the `dem print` scenario as far as it suggest to just do `dem print` ?
About not printing on the standard output, I suppose this is because the requirement *was* to print in a file.
I think we could print on the standard output, and I even think we do something similar on beeo.

**Pull request closed without merging**
